[tasks.tailwind]
workspace = false
command = "npx"
args = ["tailwindcss", "-i", "./tailwind.css", "-o", "./public/style.css", "--watch"]

[tasks.watch]
workspace = false
command = "cargo-watch"
args = ["-x","fmt","-x","run", "--package", "blogspot"]

[tasks.build]
workspace = false
command = "cargo"
args = ["build","--release", "--package", "blogspot"]

[tasks.dir]
command = "mv"
args = ["./target/release/blogspot","./server"]


[tasks.release]
workspace = false
dependencies = [
  "build",
  "dir",
]
